const musicData = {
  "행복": {
    KPOP: [
      { title: "Butter", artist: "BTS" },
      { title: "Permission to Dance", artist: "BTS" },
      { title: "Super Shy", artist: "NewJeans" },
      { title: "How Sweet", artist: "NewJeans" },
      { title: "After LIKE", artist: "IVE" },
      { title: "ELEVEN", artist: "IVE" },
      { title: "Dolphin", artist: "OH MY GIRL" },
      { title: "Dun Dun Dance", artist: "OH MY GIRL" },
      { title: "Red Flavor", artist: "Red Velvet" },
      { title: "Power Up", artist: "Red Velvet" },
      { title: "Weekend", artist: "TAEYEON" },
      { title: "Lilac", artist: "IU" },
      { title: "Blueming", artist: "IU" },
      { title: "Celebrity", artist: "IU" },
      { title: "Love Lee", artist: "AKMU" },
      { title: "200%", artist: "AKMU" },
      { title: "Very Nice", artist: "SEVENTEEN" },
      { title: "Left & Right", artist: "SEVENTEEN" },
      { title: "Fighting", artist: "BSS" },
      { title: "Rollin'", artist: "Brave Girls" },
      { title: "CHEER UP", artist: "TWICE" },
      { title: "TT", artist: "TWICE" },
      { title: "Dance The Night Away", artist: "TWICE" },
      { title: "ASAP", artist: "STAYC" },
      { title: "Teddy Bear", artist: "STAYC" },
      { title: "SNEAKERS", artist: "ITZY" },
      { title: "Bubble", artist: "STAYC" },
      { title: "Love Me Like This", artist: "NMIXX" },
      { title: "Hello Future", artist: "NCT DREAM" },
      { title: "Candy", artist: "NCT DREAM" }
    ],

    POP: [
      { title: "Sunday Morning", artist: "Maroon 5" },
      { title: "Sugar", artist: "Maroon 5" },
      { title: "Walking On Sunshine", artist: "Katrina & The Waves" },
      { title: "Good Time", artist: "Owl City & Carly Rae Jepsen" },
      { title: "Happy", artist: "Pharrell Williams" },
      { title: "Shake It Off", artist: "Taylor Swift" },
      { title: "22", artist: "Taylor Swift" },
      { title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
      { title: "I Really Like You", artist: "Carly Rae Jepsen" },
      { title: "Firework", artist: "Katy Perry" },
      { title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
      { title: "What Makes You Beautiful", artist: "One Direction" },
      { title: "Best Song Ever", artist: "One Direction" },
      { title: "Good as Hell", artist: "Lizzo" },
      { title: "On Top of the World", artist: "Imagine Dragons" },
      { title: "Best Day Of My Life", artist: "American Authors" },
      { title: "Pocketful of Sunshine", artist: "Natasha Bedingfield" },
      { title: "Unwritten", artist: "Natasha Bedingfield" },
      { title: "Put Your Records On", artist: "Corinne Bailey Rae" },
      { title: "I'm Yours", artist: "Jason Mraz" },
      { title: "Better Together", artist: "Jack Johnson" },
      { title: "Sunday Best", artist: "Surfaces" },
      { title: "Classic", artist: "MKTO" },
      { title: "Good Life", artist: "OneRepublic" },
      { title: "Beautiful Soul", artist: "Jesse McCartney" },
      { title: "Roar", artist: "Katy Perry" },
      { title: "Happy Together", artist: "The Turtles" },
      { title: "Hey, Soul Sister", artist: "Train" },
      { title: "Rude", artist: "MAGIC!" },
      { title: "Shotgun", artist: "George Ezra" }
    ]
  },

  "사랑": {
    KPOP: [
      { title: "Love wins all", artist: "IU" },
      { title: "Attention", artist: "NewJeans" },
      { title: "OMG", artist: "NewJeans" },
      { title: "LOVE DIVE", artist: "IVE" },
      { title: "Either Way", artist: "IVE" },
      { title: "Polaroid Love", artist: "ENHYPEN" },
      { title: "Fever", artist: "ENHYPEN" },
      { title: "Love Me Again", artist: "V" },
      { title: "Seven", artist: "Jung Kook" },
      { title: "Still With You", artist: "Jung Kook" },
      { title: "Boy With Luv", artist: "BTS" },
      { title: "DNA", artist: "BTS" },
      { title: "Love Scenario", artist: "iKON" },
      { title: "Me After You", artist: "Paul Kim" },
      { title: "Every day, Every Moment", artist: "Paul Kim" },
      { title: "Friday", artist: "IU" },
      { title: "Heart", artist: "IU" },
      { title: "Some", artist: "Soyou & Junggigo" },
      { title: "Love 119", artist: "RIIZE" },
      { title: "plot twist", artist: "TWS" },
      { title: "Magnetic", artist: "ILLIT" },
      { title: "Cherish (My Love)", artist: "ILLIT" },
      { title: "Cupid", artist: "FIFTY FIFTY" },
      { title: "Love, Maybe", artist: "MeloMance" },
      { title: "난 네가 아니었으면 아마 사랑 같은 건", artist: "경제환" },
      { title: "너의 모든 순간", artist: "Sung Si Kyung" },
      { title: "오디너리 러브", artist: "경제환" },
      { title: "사랑은 영화처럼", artist: "경제환" },
      { title: "우연만은 아니었을 거야", artist: "경제환" },
      { title: "오늘 이 밤이 끝나기 전에", artist: "경제환" }
    ],

    POP: [
      { title: "Perfect", artist: "Ed Sheeran" },
      { title: "Thinking Out Loud", artist: "Ed Sheeran" },
      { title: "Love Story", artist: "Taylor Swift" },
      { title: "Lover", artist: "Taylor Swift" },
      { title: "Enchanted", artist: "Taylor Swift" },
      { title: "Adore You", artist: "Harry Styles" },
      { title: "Just the Way You Are", artist: "Bruno Mars" },
      { title: "Versace on the Floor", artist: "Bruno Mars" },
      { title: "A Thousand Years", artist: "Christina Perri" },
      { title: "All of Me", artist: "John Legend" },
      { title: "Say You Won't Let Go", artist: "James Arthur" },
      { title: "I Like Me Better", artist: "Lauv" },
      { title: "Dandelions", artist: "Ruth B." },
      { title: "Kiss Me", artist: "Sixpence None the Richer" },
      { title: "Lucky", artist: "Jason Mraz & Colbie Caillat" },
      { title: "Just Give Me a Reason", artist: "P!nk" },
      { title: "Rewrite the Stars", artist: "Zac Efron & Zendaya" },
      { title: "Love Me Like You Do", artist: "Ellie Goulding" },
      { title: "Die With A Smile", artist: "Lady Gaga & Bruno Mars" },
      { title: "I Wanna Be Yours", artist: "Arctic Monkeys" },
      { title: "Until I Found You", artist: "Stephen Sanchez" },
      { title: "Can't Help Falling in Love", artist: "Elvis Presley" },
      { title: "Lover Boy", artist: "Phum Viphurit" },
      { title: "Get You", artist: "Daniel Caesar feat. Kali Uchis" },
      { title: "Glue Song", artist: "beabadoobee" },
      { title: "From The Start", artist: "Laufey" },
      { title: "Valentine", artist: "Laufey" },
      { title: "Those Eyes", artist: "New West" },
      { title: "Line Without a Hook", artist: "Ricky Montgomery" },
      { title: "I GUESS I'M IN LOVE", artist: "Clinton Kane" }
    ]
  },

  "슬픔": {
    KPOP: [
      { title: "Beautiful Goodbye", artist: "CHEN" },
      { title: "Untitled, 2014", artist: "G-DRAGON" },
      { title: "LOSER", artist: "BIGBANG" },
      { title: "Blue", artist: "BIGBANG" },
      { title: "Missing You", artist: "2NE1" },
      { title: "IF YOU", artist: "BIGBANG" },
      { title: "Eyes, Nose, Lips", artist: "TAEYANG" },
      { title: "You Were Beautiful", artist: "DAY6" },
      { title: "Congratulations", artist: "DAY6" },
      { title: "I Need Somebody", artist: "DAY6" },
      { title: "Fine", artist: "TAEYEON" },
      { title: "Lonely", artist: "2NE1" },
      { title: "한숨", artist: "LEE HI" },
      { title: "잊어버리지마", artist: "Crush" },
      { title: "사랑했지만", artist: "Kim Kwang Seok" },
      { title: "To My Youth", artist: "BOL4" },
      { title: "사랑했나봐", artist: "YB" },
      { title: "벌써 일년", artist: "Brown Eyes" },
      { title: "기억을 걷는 시간", artist: "NELL" },
      { title: "I Loved You", artist: "DAY6" },
      { title: "How can I love the heartbreak, you're the one I love", artist: "AKMU" },
      { title: "Four Seasons", artist: "TAEYEON" },
      { title: "영원할 것 같던 (Feat. Kid Wine)", artist: "경제환" },
      { title: "니가 돌아올 희망은 없다는 걸 알아", artist: "경제환" },
      { title: "마지막으로", artist: "경제환" },
      { title: "너에게 나는 아무것도 아닐 것 같아", artist: "경제환" },
      { title: "Goodbye!", artist: "경제환" },
      { title: "마지막화", artist: "경제환" },
      { title: "사랑한단 말 다른 사람에게로", artist: "경제환" },
      { title: "이렇게 시간은 또 가겠지만", artist: "경제환" }
    ],

    POP: [
      { title: "Let Her Go", artist: "Passenger" },
      { title: "drivers license", artist: "Olivia Rodrigo" },
      { title: "Someone You Loved", artist: "Lewis Capaldi" },
      { title: "when the party's over", artist: "Billie Eilish" },
      { title: "Another Love", artist: "Tom Odell" },
      { title: "The Night We Met", artist: "Lord Huron" },
      { title: "Lovely", artist: "Billie Eilish & Khalid" },
      { title: "Happier Than Ever", artist: "Billie Eilish" },
      { title: "All I Want", artist: "Kodaline" },
      { title: "Before You Go", artist: "Lewis Capaldi" },
      { title: "Bruises", artist: "Lewis Capaldi" },
      { title: "Arcade", artist: "Duncan Laurence" },
      { title: "Dancing With Your Ghost", artist: "Sasha Alex Sloan" },
      { title: "This Town", artist: "Niall Horan" },
      { title: "Let Me Down Slowly", artist: "Alec Benjamin" },
      { title: "When I Was Your Man", artist: "Bruno Mars" },
      { title: "Talking to the Moon", artist: "Bruno Mars" },
      { title: "The Scientist", artist: "Coldplay" },
      { title: "Falling", artist: "Harry Styles" },
      { title: "Sign of the Times", artist: "Harry Styles" },
      { title: "traitor", artist: "Olivia Rodrigo" },
      { title: "deja vu", artist: "Olivia Rodrigo" },
      { title: "Someone Like You", artist: "Adele" },
      { title: "Easy On Me", artist: "Adele" },
      { title: "All Too Well", artist: "Taylor Swift" },
      { title: "exile", artist: "Taylor Swift feat. Bon Iver" },
      { title: "Liability", artist: "Lorde" },
      { title: "Skinny Love", artist: "Birdy" },
      { title: "Say Something", artist: "A Great Big World & Christina Aguilera" },
      { title: "The One That Got Away", artist: "Katy Perry" }
    ]
  },

  "화남": {
    KPOP: [
      { title: "God's Menu", artist: "Stray Kids" },
      { title: "MANIAC", artist: "Stray Kids" },
      { title: "Thunderous", artist: "Stray Kids" },
      { title: "Back Door", artist: "Stray Kids" },
      { title: "MIROH", artist: "Stray Kids" },
      { title: "Guerrilla", artist: "ATEEZ" },
      { title: "WONDERLAND", artist: "ATEEZ" },
      { title: "HALAZIA", artist: "ATEEZ" },
      { title: "BANG BANG BANG", artist: "BIGBANG" },
      { title: "FANTASTIC BABY", artist: "BIGBANG" },
      { title: "MIC Drop", artist: "BTS" },
      { title: "Not Today", artist: "BTS" },
      { title: "ON", artist: "BTS" },
      { title: "Black Mamba", artist: "aespa" },
      { title: "Next Level", artist: "aespa" },
      { title: "Savage", artist: "aespa" },
      { title: "Drama", artist: "aespa" },
      { title: "Spicy", artist: "aespa" },
      { title: "TOMBOY", artist: "(G)I-DLE" },
      { title: "Nxde", artist: "(G)I-DLE" },
      { title: "Super Lady", artist: "(G)I-DLE" },
      { title: "ANTIFRAGILE", artist: "LE SSERAFIM" },
      { title: "UNFORGIVEN", artist: "LE SSERAFIM" },
      { title: "Eve, Psyche & The Bluebeard's wife", artist: "LE SSERAFIM" },
      { title: "Kick It", artist: "NCT 127" },
      { title: "Cherry Bomb", artist: "NCT 127" },
      { title: "CRAZY", artist: "LE SSERAFIM" },
      { title: "Baddie", artist: "IVE" },
      { title: "Girls", artist: "aespa" },
      { title: "WOKE UP", artist: "XG" }
    ],

    POP: [
      { title: "Believer", artist: "Imagine Dragons" },
      { title: "Natural", artist: "Imagine Dragons" },
      { title: "Thunder", artist: "Imagine Dragons" },
      { title: "Warriors", artist: "Imagine Dragons" },
      { title: "Radioactive", artist: "Imagine Dragons" },
      { title: "Centuries", artist: "Fall Out Boy" },
      { title: "The Phoenix", artist: "Fall Out Boy" },
      { title: "Immortals", artist: "Fall Out Boy" },
      { title: "My Songs Know What You Did in the Dark (Light Em Up)", artist: "Fall Out Boy" },
      { title: "Animals", artist: "Maroon 5" },
      { title: "Look What You Made Me Do", artist: "Taylor Swift" },
      { title: "Bad Blood", artist: "Taylor Swift" },
      { title: "Therefore I Am", artist: "Billie Eilish" },
      { title: "you should see me in a crown", artist: "Billie Eilish" },
      { title: "bad guy", artist: "Billie Eilish" },
      { title: "HUMBLE.", artist: "Kendrick Lamar" },
      { title: "Lose Yourself", artist: "Eminem" },
      { title: "Till I Collapse", artist: "Eminem" },
      { title: "Numb", artist: "Linkin Park" },
      { title: "In the End", artist: "Linkin Park" },
      { title: "What I've Done", artist: "Linkin Park" },
      { title: "Smells Like Teen Spirit", artist: "Nirvana" },
      { title: "Break Stuff", artist: "Limp Bizkit" },
      { title: "Misery Business", artist: "Paramore" },
      { title: "Monster", artist: "Skillet" },
      { title: "Animal I Have Become", artist: "Three Days Grace" },
      { title: "I Hate Everything About You", artist: "Three Days Grace" },
      { title: "Bring Me to Life", artist: "Evanescence" },
      { title: "The Pretender", artist: "Foo Fighters" },
      { title: "Killing In The Name", artist: "Rage Against the Machine" }
    ]
  },

  "피곤": {
    KPOP: [
      { title: "Ditto", artist: "NewJeans" },
      { title: "Through the Night", artist: "IU" },
      { title: "11:11", artist: "TAEYEON" },
      { title: "Palette", artist: "IU" },
      { title: "strawberry moon", artist: "IU" },
      { title: "Instagram", artist: "DEAN" },
      { title: "D (Half Moon)", artist: "DEAN" },
      { title: "Galaxy", artist: "BOL4" },
      { title: "Only", artist: "LEE HI" },
      { title: "Fairy of Shampoo", artist: "TXT" },
      { title: "Nap of a star", artist: "TXT" },
      { title: "20cm", artist: "TXT" },
      { title: "Magic Island", artist: "TXT" },
      { title: "Coffee", artist: "BTS" },
      { title: "Butterfly", artist: "BTS" },
      { title: "Serendipity", artist: "Jimin" },
      { title: "Love Again", artist: "Baekhyun" },
      { title: "UN Village", artist: "Baekhyun" },
      { title: "Handle It", artist: "TWICE" },
      { title: "Automatic", artist: "Red Velvet" },
      { title: "One of These Nights", artist: "Red Velvet" },
      { title: "Rain", artist: "TAEYEON" },
      { title: "Restless", artist: "BIBI" },
      { title: "WA-R-R", artist: "Colde" },
      { title: "bath", artist: "offonoff" },
      { title: "lovememore.", artist: "dosii" },
      { title: "seasons", artist: "wave to earth" },
      { title: "peach eyes", artist: "wave to earth" },
      { title: "Peaches", artist: "KAI" },
      { title: "Daydream", artist: "Dreamcatcher" }
    ],

    POP: [
      { title: "golden hour", artist: "JVKE" },
      { title: "comethru", artist: "Jeremy Zucker" },
      { title: "Heather", artist: "Conan Gray" },
      { title: "People Watching", artist: "Conan Gray" },
      { title: "Memories", artist: "Conan Gray" },
      { title: "Sunkissed", artist: "khai dreams" },
      { title: "Paris in the Rain", artist: "Lauv" },
      { title: "Mean It", artist: "Lauv" },
      { title: "From The Dining Table", artist: "Harry Styles" },
      { title: "Sweet Creature", artist: "Harry Styles" },
      { title: "Photograph", artist: "Ed Sheeran" },
      { title: "Location Unknown", artist: "HONNE" },
      { title: "Day 1 ◑", artist: "HONNE" },
      { title: "Warm On A Cold Night", artist: "HONNE" },
      { title: "La La Lost You", artist: "NIKI" },
      { title: "lowkey", artist: "NIKI" },
      { title: "Moon River", artist: "Frank Ocean" },
      { title: "Pink + White", artist: "Frank Ocean" },
      { title: "Slow Dancing in the Dark", artist: "Joji" },
      { title: "Sanctuary", artist: "Joji" },
      { title: "Die For You", artist: "The Weeknd" },
      { title: "Out of Time", artist: "The Weeknd" },
      { title: "Moon Song", artist: "Phoebe Bridgers" },
      { title: "Like Real People Do", artist: "Hozier" },
      { title: "Mystery of Love", artist: "Sufjan Stevens" },
      { title: "Bloom", artist: "The Paper Kites" },
      { title: "Heartbeats", artist: "José González" },
      { title: "Anchor", artist: "Novo Amor" },
      { title: "Cherry Wine", artist: "Hozier" },
      { title: "Show Me How", artist: "Men I Trust" }
    ]
  },

  "위로": {
    KPOP: [
      { title: "밤편지", artist: "IU" },
      { title: "Love Poem", artist: "IU" },
      { title: "Eight", artist: "IU" },
      { title: "Dear Name", artist: "IU" },
      { title: "My Sea", artist: "IU" },
      { title: "Breathe", artist: "LEE HI" },
      { title: "HOLO", artist: "LEE HI" },
      { title: "그대라는 시", artist: "TAEYEON" },
      { title: "Still Life", artist: "BIGBANG" },
      { title: "Zombie", artist: "DAY6" },
      { title: "Beautiful", artist: "Crush" },
      { title: "Home", artist: "SEVENTEEN" },
      { title: "Hug", artist: "SEVENTEEN" },
      { title: "Magic Shop", artist: "BTS" },
      { title: "Answer: Love Myself", artist: "BTS" },
      { title: "Life Goes On", artist: "BTS" },
      { title: "Spring Day", artist: "BTS" },
      { title: "My Youth", artist: "NCT DREAM" },
      { title: "Rainbow", artist: "NCT DREAM" },
      { title: "That's okay", artist: "D.O." },
      { title: "걱정에서 어른까지", artist: "경제환" },
      { title: "그럴 때가 오겠지", artist: "경제환" },
      { title: "가끔 안부는 들려주길", artist: "ALEPH & 경제환" },
      { title: "Time of Our Life", artist: "DAY6" },
      { title: "End of a day", artist: "JONGHYUN" },
      { title: "00:00 (Zero O'Clock)", artist: "BTS" },
      { title: "Epiphany", artist: "Jin" },
      { title: "everythingoes", artist: "RM" },
      { title: "It's Okay", artist: "BTOB" },
      { title: "Dear Me", artist: "TAEYEON" }
    ],

    POP: [
      { title: "Fix You", artist: "Coldplay" },
      { title: "Yellow", artist: "Coldplay" },
      { title: "Count on Me", artist: "Bruno Mars" },
      { title: "Lean on Me", artist: "Bill Withers" },
      { title: "You Say", artist: "Lauren Daigle" },
      { title: "Rise Up", artist: "Andra Day" },
      { title: "A Million Dreams", artist: "P!nk" },
      { title: "Castle on the Hill", artist: "Ed Sheeran" },
      { title: "Vienna", artist: "Billy Joel" },
      { title: "The Climb", artist: "Miley Cyrus" },
      { title: "Fight Song", artist: "Rachel Platten" },
      { title: "Scars to Your Beautiful", artist: "Alessia Cara" },
      { title: "Brave", artist: "Sara Bareilles" },
      { title: "Try", artist: "P!nk" },
      { title: "Keep Holding On", artist: "Avril Lavigne" },
      { title: "Somewhere Only We Know", artist: "Keane" },
      { title: "Home", artist: "Michael Bublé" },
      { title: "Rainbow", artist: "Kacey Musgraves" },
      { title: "Beautiful", artist: "Christina Aguilera" },
      { title: "You Raise Me Up", artist: "Josh Groban" },
      { title: "Hero", artist: "Mariah Carey" },
      { title: "Stand by Me", artist: "Ben E. King" },
      { title: "What a Wonderful World", artist: "Louis Armstrong" },
      { title: "Here Comes the Sun", artist: "The Beatles" },
      { title: "Let It Be", artist: "The Beatles" },
      { title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel" },
      { title: "You've Got a Friend", artist: "Carole King" },
      { title: "Landslide", artist: "Fleetwood Mac" },
      { title: "I Won't Give Up", artist: "Jason Mraz" },
      { title: "Better Days", artist: "OneRepublic" }
    ]
  },

  "신남": {
    KPOP: [
      { title: "APT.", artist: "ROSÉ & Bruno Mars" },
      { title: "Dynamite", artist: "BTS" },
      { title: "Fire", artist: "BTS" },
      { title: "Hype Boy", artist: "NewJeans" },
      { title: "I AM", artist: "IVE" },
      { title: "Queencard", artist: "(G)I-DLE" },
      { title: "EASY", artist: "LE SSERAFIM" },
      { title: "HOT", artist: "SEVENTEEN" },
      { title: "Energetic", artist: "Wanna One" },
      { title: "Supernova", artist: "aespa" },
      { title: "Whiplash", artist: "aespa" },
      { title: "BBoom BBoom", artist: "MOMOLAND" },
      { title: "DDU-DU DDU-DU", artist: "BLACKPINK" },
      { title: "Kill This Love", artist: "BLACKPINK" },
      { title: "Pink Venom", artist: "BLACKPINK" },
      { title: "How You Like That", artist: "BLACKPINK" },
      { title: "LALISA", artist: "LISA" },
      { title: "MONEY", artist: "LISA" },
      { title: "MIROTIC", artist: "TVXQ!" },
      { title: "Growl", artist: "EXO" },
      { title: "Love Shot", artist: "EXO" },
      { title: "Ring Ding Dong", artist: "SHINee" },
      { title: "Lucifer", artist: "SHINee" },
      { title: "Sorry, Sorry", artist: "SUPER JUNIOR" },
      { title: "Gee", artist: "Girls' Generation" },
      { title: "Genie", artist: "Girls' Generation" },
      { title: "STEP", artist: "KARA" },
      { title: "Mister", artist: "KARA" },
      { title: "Up & Down", artist: "EXID" },
      { title: "Gashina", artist: "SUNMI" }
    ],

    POP: [
      { title: "Uptown Funk", artist: "Mark Ronson feat. Bruno Mars" },
      { title: "Don't Start Now", artist: "Dua Lipa" },
      { title: "Levitating", artist: "Dua Lipa" },
      { title: "Blinding Lights", artist: "The Weeknd" },
      { title: "24K Magic", artist: "Bruno Mars" },
      { title: "Treasure", artist: "Bruno Mars" },
      { title: "Locked Out of Heaven", artist: "Bruno Mars" },
      { title: "Shut Up and Dance", artist: "WALK THE MOON" },
      { title: "Wake Me Up", artist: "Avicii" },
      { title: "The Nights", artist: "Avicii" },
      { title: "Levels", artist: "Avicii" },
      { title: "Rather Be", artist: "Clean Bandit feat. Jess Glynne" },
      { title: "Dance Monkey", artist: "Tones and I" },
      { title: "Watermelon Sugar", artist: "Harry Styles" },
      { title: "Don't Stop Me Now", artist: "Queen" },
      { title: "Dancing Queen", artist: "ABBA" },
      { title: "Mamma Mia", artist: "ABBA" },
      { title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
      { title: "Party Rock Anthem", artist: "LMFAO" },
      { title: "Timber", artist: "Pitbull feat. Kesha" },
      { title: "Cake By The Ocean", artist: "DNCE" },
      { title: "We Found Love", artist: "Rihanna feat. Calvin Harris" },
      { title: "Titanium", artist: "David Guetta feat. Sia" },
      { title: "One Kiss", artist: "Calvin Harris & Dua Lipa" },
      { title: "Don't You Worry Child", artist: "Swedish House Mafia feat. John Martin" },
      { title: "Feel So Close", artist: "Calvin Harris" },
      { title: "TiK ToK", artist: "Kesha" },
      { title: "Raise Your Glass", artist: "P!nk" },
      { title: "Starships", artist: "Nicki Minaj" },
      { title: "Dynamite", artist: "Taio Cruz" }
    ]
  },

  "SHARK": {
    KPOP: [
      { title: "Wave", artist: "ATEEZ" },
      { title: "Ocean View", artist: "Rothy" },
      { title: "Island", artist: "WINNER" },
      { title: "Summer 127", artist: "NCT 127" },
      { title: "Why So Lonely", artist: "Wonder Girls" },
      { title: "Beach Again", artist: "SSAK3" },
      { title: "Travel", artist: "BOL4" },
      { title: "Surf", artist: "ITZY" },
      { title: "View", artist: "SHINee" },
      { title: "Our Summer", artist: "TXT" },
      { title: "Blue Hour", artist: "TXT" },
      { title: "Pool", artist: "WOODZ" },
      { title: "Swimming", artist: "JEON SOMI" },
      { title: "Island", artist: "Yerin Baek" },
      { title: "Popo (How deep is our love?)", artist: "Yerin Baek" },
      { title: "Square (2017)", artist: "Yerin Baek" },
      { title: "Night Drive", artist: "Red Velvet" },
      { title: "Ghosting", artist: "TXT" },
      { title: "Opening Sequence", artist: "TXT" },
      { title: "Farewell, Neverland", artist: "TXT" },
      { title: "Virtual Angel", artist: "ARTMS" },
      { title: "Icarus", artist: "ARTMS" },
      { title: "Running Through The Night", artist: "Seori" },
      { title: "So Beautiful", artist: "DPR IAN" },
      { title: "No Blueberries", artist: "DPR IAN" },
      { title: "dayfly", artist: "DEAN feat. Sulli & Rad Museum" },
      { title: "외딴 별과 위성", artist: "경제환" },
      { title: "인터넷 속 너의 Blue", artist: "경제환" },
      { title: "Dandelion", artist: "OOHYO" },
      { title: "비 lI!l", artist: "경제환" }
    ],

    POP: [
      { title: "Ocean Eyes", artist: "Billie Eilish" },
      { title: "Ocean", artist: "Martin Garrix feat. Khalid" },
      { title: "Waves", artist: "Dean Lewis" },
      { title: "Ocean Drive", artist: "Duke Dumont" },
      { title: "A Drop In The Ocean", artist: "Ron Pope" },
      { title: "Island In The Sun", artist: "Weezer" },
      { title: "Walking On A Dream", artist: "Empire of the Sun" },
      { title: "Malibu", artist: "Miley Cyrus" },
      { title: "Summertime Sadness", artist: "Lana Del Rey" },
      { title: "Riptide", artist: "Vance Joy" },
      { title: "The Ocean", artist: "Mike Perry feat. Shy Martin" },
      { title: "Sunset Lover", artist: "Petit Biscuit" },
      { title: "Firestone", artist: "Kygo feat. Conrad Sewell" },
      { title: "Stole the Show", artist: "Kygo feat. Parson James" },
      { title: "Island", artist: "The xx" },
      { title: "Feels Like Summer", artist: "Childish Gambino" },
      { title: "Every Summertime", artist: "NIKI" },
      { title: "Midnight City", artist: "M83" },
      { title: "After Dark", artist: "Mr.Kitty" },
      { title: "Space Song", artist: "Beach House" },
      { title: "Myth", artist: "Beach House" },
      { title: "Apocalypse", artist: "Cigarettes After Sex" },
      { title: "Sunsetz", artist: "Cigarettes After Sex" },
      { title: "Heavenly", artist: "Cigarettes After Sex" },
      { title: "No One Noticed", artist: "The Marías" },
      { title: "Only in My Dreams", artist: "The Marías" },
      { title: "Intro", artist: "The xx" },
      { title: "West Coast", artist: "Lana Del Rey" },
      { title: "Innerbloom", artist: "RÜFÜS DU SOL" },
      { title: "Sunroof", artist: "Nicky Youre & dazy" }
    ]
  }
};
