const musicData = {

  "행복": {

    KPOP: [
      { title: "Dynamite", artist: "BTS" },
      { title: "Butter", artist: "BTS" },
      { title: "Permission to Dance", artist: "BTS" },
      { title: "Super Shy", artist: "NewJeans" },
      { title: "Hype Boy", artist: "NewJeans" },
      { title: "Attention", artist: "NewJeans" },
      { title: "How Sweet", artist: "NewJeans" },
      { title: "OMG", artist: "NewJeans" },
      { title: "After LIKE", artist: "IVE" },
      { title: "LOVE DIVE", artist: "IVE" },
      { title: "I AM", artist: "IVE" },
      { title: "ELEVEN", artist: "IVE" },
      { title: "Queencard", artist: "(G)I-DLE" },
      { title: "TOMBOY", artist: "(G)I-DLE" },
      { title: "Dolphin", artist: "OH MY GIRL" },
      { title: "Dun Dun Dance", artist: "OH MY GIRL" },
      { title: "Feel My Rhythm", artist: "Red Velvet" },
      { title: "Red Flavor", artist: "Red Velvet" },
      { title: "Power Up", artist: "Red Velvet" },
      { title: "Weekend", artist: "TAEYEON" },
      { title: "Lilac", artist: "IU" },
      { title: "Blueming", artist: "IU" },
      { title: "Celebrity", artist: "IU" },
      { title: "Love Lee", artist: "AKMU" },
      { title: "200%", artist: "AKMU" },
      { title: "Energetic", artist: "Wanna One" },
      { title: "Very Nice", artist: "SEVENTEEN" },
      { title: "Left & Right", artist: "SEVENTEEN" },
      { title: "God's Menu", artist: "Stray Kids" },
      { title: "Fighting", artist: "BSS" }
    ],

    POP: [
      { title: "Sunday Morning", artist: "Maroon 5" },
      { title: "Sugar", artist: "Maroon 5" },
      { title: "Moves Like Jagger", artist: "Maroon 5" },
      { title: "Walking On Sunshine", artist: "Katrina & The Waves" },
      { title: "Good Time", artist: "Owl City & Carly Rae Jepsen" },
      { title: "Best Day Of My Life", artist: "American Authors" },
      { title: "Happy", artist: "Pharrell Williams" },
      { title: "Count on Me", artist: "Bruno Mars" },
      { title: "Just the Way You Are", artist: "Bruno Mars" },
      { title: "Treasure", artist: "Bruno Mars" },
      { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars" },
      { title: "Shake It Off", artist: "Taylor Swift" },
      { title: "22", artist: "Taylor Swift" },
      { title: "Cruel Summer", artist: "Taylor Swift" },
      { title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
      { title: "I Really Like You", artist: "Carly Rae Jepsen" },
      { title: "Teenage Dream", artist: "Katy Perry" },
      { title: "California Gurls", artist: "Katy Perry" },
      { title: "Firework", artist: "Katy Perry" },
      { title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
      { title: "Love Yourself", artist: "Justin Bieber" },
      { title: "What Makes You Beautiful", artist: "One Direction" },
      { title: "Story of My Life", artist: "One Direction" },
      { title: "Dance Monkey", artist: "Tones and I" },
      { title: "Levitating", artist: "Dua Lipa" },
      { title: "Don't Start Now", artist: "Dua Lipa" },
      { title: "Good as Hell", artist: "Lizzo" },
      { title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
      { title: "On Top of the World", artist: "Imagine Dragons" },
      { title: "Best Song Ever", artist: "One Direction" }
    ]

  },


  "사랑": {

    KPOP: [
      { title: "Love wins all", artist: "IU" },
      { title: "Ditto", artist: "NewJeans" },
      { title: "OMG", artist: "NewJeans" },
      { title: "Attention", artist: "NewJeans" },
      { title: "LOVE DIVE", artist: "IVE" },
      { title: "I AM", artist: "IVE" },
      { title: "Either Way", artist: "IVE" },
      { title: "Polaroid Love", artist: "ENHYPEN" },
      { title: "Fever", artist: "ENHYPEN" },
      { title: "Love Me Again", artist: "V" },
      { title: "Seven", artist: "Jung Kook" },
      { title: "Still With You", artist: "Jung Kook" },
      { title: "Boy With Luv", artist: "BTS" },
      { title: "DNA", artist: "BTS" },
      { title: "Spring Day", artist: "BTS" },
      { title: "I Need U", artist: "BTS" },
      { title: "Love Scenario", artist: "iKON" },
      { title: "All For You", artist: "SECHSKIES" },
      { title: "Me After You", artist: "Paul Kim" },
      { title: "Every day, Every Moment", artist: "Paul Kim" },
      { title: "Beautiful", artist: "Crush" },
      { title: "Beautiful Goodbye", artist: "Chen" },
      { title: "Through the Night", artist: "IU" },
      { title: "Friday", artist: "IU" },
      { title: "Heart", artist: "IU" },
      { title: "Love Lee", artist: "AKMU" },
      { title: "200%", artist: "AKMU" },
      { title: "D (Half Moon)", artist: "DEAN" },
      { title: "Instagram", artist: "DEAN" },
      { title: "Some", artist: "Soyou & Junggigo" }
    ],

    POP: [
      { title: "Perfect", artist: "Ed Sheeran" },
      { title: "Thinking Out Loud", artist: "Ed Sheeran" },
      { title: "Photograph", artist: "Ed Sheeran" },
      { title: "Until I Found You", artist: "Stephen Sanchez" },
      { title: "Love Story", artist: "Taylor Swift" },
      { title: "Lover", artist: "Taylor Swift" },
      { title: "Enchanted", artist: "Taylor Swift" },
      { title: "Adore You", artist: "Harry Styles" },
      { title: "As It Was", artist: "Harry Styles" },
      { title: "Just the Way You Are", artist: "Bruno Mars" },
      { title: "Versace on the Floor", artist: "Bruno Mars" },
      { title: "Talking to the Moon", artist: "Bruno Mars" },
      { title: "A Thousand Years", artist: "Christina Perri" },
      { title: "All of Me", artist: "John Legend" },
      { title: "Say You Won't Let Go", artist: "James Arthur" },
      { title: "I Like Me Better", artist: "Lauv" },
      { title: "Paris in the Rain", artist: "Lauv" },
      { title: "Dandelions", artist: "Ruth B." },
      { title: "Until I Found You", artist: "Stephen Sanchez" },
      { title: "Kiss Me", artist: "Sixpence None the Richer" },
      { title: "Lucky", artist: "Jason Mraz & Colbie Caillat" },
      { title: "I'm Yours", artist: "Jason Mraz" },
      { title: "Just Give Me a Reason", artist: "P!nk" },
      { title: "Rewrite the Stars", artist: "Zac Efron & Zendaya" },
      { title: "Love Me Like You Do", artist: "Ellie Goulding" },
      { title: "A Sky Full of Stars", artist: "Coldplay" },
      { title: "Yellow", artist: "Coldplay" },
      { title: "The Scientist", artist: "Coldplay" },
      { title: "Die With A Smile", artist: "Lady Gaga & Bruno Mars" },
      { title: "I Wanna Be Yours", artist: "Arctic Monkeys" }
    ]

  },


  "슬픔": {

    KPOP: [
      { title: "밤편지", artist: "IU" },
      { title: "Love Poem", artist: "IU" },
      { title: "Through the Night", artist: "IU" },
      { title: "Eight", artist: "IU" },
      { title: "To My Youth", artist: "BOL4" },
      { title: "Lonely", artist: "2NE1" },
      { title: "Beautiful Goodbye", artist: "Chen" },
      { title: "Untitled, 2014", artist: "G-DRAGON" },
      { title: "Loser", artist: "BIGBANG" },
      { title: "Blue", artist: "BIGBANG" },
      { title: "Missing You", artist: "2NE1" },
      { title: "If You", artist: "BIGBANG" },
      { title: "Eyes, Nose, Lips", artist: "TAEYANG" },
      { title: "You Were Beautiful", artist: "DAY6" },
      { title: "Congratulations", artist: "DAY6" },
      { title: "I Need Somebody", artist: "DAY6" },
      { title: "Zombie", artist: "DAY6" },
      { title: "Fine", artist: "TAEYEON" },
      { title: "11:11", artist: "TAEYEON" },
      { title: "Rain", artist: "TAEYEON" },
      { title: "Lonely", artist: "JONGHYUN & TAEYEON" },
      { title: "Breathe", artist: "LEE HI" },
      { title: "HOLO", artist: "LEE HI" },
      { title: "한숨", artist: "LEE HI" },
      { title: "잊어버리지마", artist: "Crush" },
      { title: "Beautiful", artist: "Crush" },
      { title: "그대라는 시", artist: "TAEYEON" },
      { title: "사랑했지만", artist: "Kim Kwang Seok" },
      { title: "너의 모든 순간", artist: "Sung Si Kyung" },
      { title: "너를 만나", artist: "Paul Kim" }
    ],

    POP: [
      { title: "Let Her Go", artist: "Passenger" },
      { title: "drivers license", artist: "Olivia Rodrigo" },
      { title: "Someone You Loved", artist: "Lewis Capaldi" },
      { title: "when the party's over", artist: "Billie Eilish" },
      { title: "Another Love", artist: "Tom Odell" },
      { title: "The Night We Met", artist: "Lord Huron" },
      { title: "Lovely", artist: "Billie Eilish & Khalid" },
      { title: "Happier Than Ever", artist: "Billie Eilish" },
      { title: "Ocean Eyes", artist: "Billie Eilish" },
      { title: "idontwannabeyouanymore", artist: "Billie Eilish" },
      { title: "All I Want", artist: "Kodaline" },
      { title: "Before You Go", artist: "Lewis Capaldi" },
      { title: "Bruises", artist: "Lewis Capaldi" },
      { title: "Arcade", artist: "Duncan Laurence" },
      { title: "Dancing With Your Ghost", artist: "Sasha Alex Sloan" },
      { title: "This Town", artist: "Niall Horan" },
      { title: "Let Me Down Slowly", artist: "Alec Benjamin" },
      { title: "If I Killed Someone For You", artist: "Alec Benjamin" },
      { title: "when i was your man", artist: "Bruno Mars" },
      { title: "Talking to the Moon", artist: "Bruno Mars" },
      { title: "Fix You", artist: "Coldplay" },
      { title: "The Scientist", artist: "Coldplay" },
      { title: "Falling", artist: "Harry Styles" },
      { title: "Sign of the Times", artist: "Harry Styles" },
      { title: "traitor", artist: "Olivia Rodrigo" },
      { title: "deja vu", artist: "Olivia Rodrigo" },
      { title: "Someone Like You", artist: "Adele" },
      { title: "Easy On Me", artist: "Adele" },
      { title: "All Too Well", artist: "Taylor Swift" },
      { title: "exile", artist: "Taylor Swift ft. Bon Iver" }
    ]

  },


  "화남": {

    KPOP: [
      { title: "God's Menu", artist: "Stray Kids" },
      { title: "MANIAC", artist: "Stray Kids" },
      { title: "Thunderous", artist: "Stray Kids" },
      { title: "Back Door", artist: "Stray Kids" },
      { title: "MIROH", artist: "Stray Kids" },
      { title: "Guerrilla", artist: "ATEEZ" },
      { title: "Wonderland", artist: "ATEEZ" },
      { title: "HALAZIA", artist: "ATEEZ" },
      { title: "BANG BANG BANG", artist: "BIGBANG" },
      { title: "Fantastic Baby", artist: "BIGBANG" },
      { title: "MIC Drop", artist: "BTS" },
      { title: "Fire", artist: "BTS" },
      { title: "Not Today", artist: "BTS" },
      { title: "ON", artist: "BTS" },
      { title: "Black Mamba", artist: "aespa" },
      { title: "Next Level", artist: "aespa" },
      { title: "Savage", artist: "aespa" },
      { title: "Drama", artist: "aespa" },
      { title: "Spicy", artist: "aespa" },
      { title: "TOMBOY", artist: "(G)I-DLE" },
      { title: "Nxde", artist: "(G)I-DLE" },
      { title: "Super Lady", artist: "(G)I-DLE" },
      { title: "ANTIFRAGILE", artist: "LE SSERAFIM" },
      { title: "UNFORGIVEN", artist: "LE SSERAFIM" },
      { title: "Eve, Psyche & The Bluebeard's wife", artist: "LE SSERAFIM" },
      { title: "I AM", artist: "IVE" },
      { title: "Baddie", artist: "IVE" },
      { title: "Crazy", artist: "LE SSERAFIM" },
      { title: "Kick It", artist: "NCT 127" },
      { title: "Cherry Bomb", artist: "NCT 127" }
    ],

    POP: [
      { title: "Believer", artist: "Imagine Dragons" },
      { title: "Natural", artist: "Imagine Dragons" },
      { title: "Thunder", artist: "Imagine Dragons" },
      { title: "Warriors", artist: "Imagine Dragons" },
      { title: "Radioactive", artist: "Imagine Dragons" },
      { title: "Centuries", artist: "Fall Out Boy" },
      { title: "The Phoenix", artist: "Fall Out Boy" },
      { title: "Immortals", artist: "Fall Out Boy" },
      { title: "My Songs Know What You Did in the Dark", artist: "Fall Out Boy" },
      { title: "Radioactive", artist: "Imagine Dragons" },
      { title: "Animals", artist: "Maroon 5" },
      { title: "Look What You Made Me Do", artist: "Taylor Swift" },
      { title: "Bad Blood", artist: "Taylor Swift" },
      { title: "You Need To Calm Down", artist: "Taylor Swift" },
      { title: "Therefore I Am", artist: "Billie Eilish" },
      { title: "you should see me in a crown", artist: "Billie Eilish" },
      { title: "Bad Guy", artist: "Billie Eilish" },
      { title: "HUMBLE.", artist: "Kendrick Lamar" },
      { title: "Lose Yourself", artist: "Eminem" },
      { title: "Till I Collapse", artist: "Eminem" },
      { title: "Numb", artist: "Linkin Park" },
      { title: "In the End", artist: "Linkin Park" },
      { title: "What I've Done", artist: "Linkin Park" },
      { title: "Smells Like Teen Spirit", artist: "Nirvana" },
      { title: "Break Stuff", artist: "Limp Bizkit" },
      { title: "My Songs Know What You Did in the Dark", artist: "Fall Out Boy" },
      { title: "Centuries", artist: "Fall Out Boy" },
      { title: "Misery Business", artist: "Paramore" },
      { title: "Monster", artist: "Skillet" },
      { title: "Animal I Have Become", artist: "Three Days Grace" }
    ]

  },


  "피곤": {

    KPOP: [
      { title: "Ditto", artist: "NewJeans" },
      { title: "밤편지", artist: "IU" },
      { title: "Love Lee", artist: "AKMU" },
      { title: "Through the Night", artist: "IU" },
      { title: "11:11", artist: "TAEYEON" },
      { title: "Palette", artist: "IU" },
      { title: "strawberry moon", artist: "IU" },
      { title: "Instagram", artist: "DEAN" },
      { title: "D (Half Moon)", artist: "DEAN" },
      { title: "Galaxy", artist: "BOL4" },
      { title: "Some", artist: "Soyou & Junggigo" },
      { title: "Only", artist: "LEE HI" },
      { title: "HOLO", artist: "LEE HI" },
      { title: "Breathe", artist: "LEE HI" },
      { title: "Fairy of Shampoo", artist: "TXT" },
      { title: "Nap of a star", artist: "TXT" },
      { title: "20cm", artist: "TXT" },
      { title: "Magic Island", artist: "TXT" },
      { title: "Coffee", artist: "BTS" },
      { title: "Butterfly", artist: "BTS" },
      { title: "Spring Day", artist: "BTS" },
      { title: "Serendipity", artist: "Jimin" },
      { title: "Love Again", artist: "Baekhyun" },
      { title: "UN Village", artist: "Baekhyun" },
      { title: "What Is Love?", artist: "TWICE" },
      { title: "Handle It", artist: "TWICE" },
      { title: "Automatic", artist: "Red Velvet" },
      { title: "One of These Nights", artist: "Red Velvet" },
      { title: "11:11", artist: "TAEYEON" },
      { title: "Rain", artist: "TAEYEON" }
    ],

    POP: [
      { title: "golden hour", artist: "JVKE" },
      { title: "Until I Found You", artist: "Stephen Sanchez" },
      { title: "comethru", artist: "Jeremy Zucker" },
      { title: "Ocean Eyes", artist: "Billie Eilish" },
      { title: "The Night We Met", artist: "Lord Huron" },
      { title: "Heather", artist: "Conan Gray" },
      { title: "People Watching", artist: "Conan Gray" },
      { title: "Memories", artist: "Conan Gray" },
      { title: "Sunkissed", artist: "khai dreams" },
      { title: "I Like Me Better", artist: "Lauv" },
      { title: "Paris in the Rain", artist: "Lauv" },
      { title: "Mean It", artist: "Lauv" },
      { title: "From The Dining Table", artist: "Harry Styles" },
      { title: "Falling", artist: "Harry Styles" },
      { title: "Sweet Creature", artist: "Harry Styles" },
      { title: "Photograph", artist: "Ed Sheeran" },
      { title: "Perfect", artist: "Ed Sheeran" },
      { title: "Best Part", artist: "Daniel Caesar ft. H.E.R." },
      { title: "Location Unknown", artist: "HONNE" },
      { title: "Day 1 ◑", artist: "HONNE" },
      { title: "Warm On A Cold Night", artist: "HONNE" },
      { title: "La La Lost You", artist: "NIKI" },
      { title: "Every Summertime", artist: "NIKI" },
      { title: "lowkey", artist: "NIKI" },
      { title: "Moon River", artist: "Frank Ocean" },
      { title: "Pink + White", artist: "Frank Ocean" },
      { title: "Slow Dancing in the Dark", artist: "Joji" },
      { title: "Sanctuary", artist: "Joji" },
      { title: "Die For You", artist: "The Weeknd" },
      { title: "Out of Time", artist: "The Weeknd" }
    ]

  },


  "위로": {

    KPOP: [
      { title: "밤편지", artist: "IU" },
      { title: "Love Poem", artist: "IU" },
      { title: "Eight", artist: "IU" },
      { title: "Through the Night", artist: "IU" },
      { title: "Dear Name", artist: "IU" },
      { title: "My Sea", artist: "IU" },
      { title: "To My Youth", artist: "BOL4" },
      { title: "You Are My Everything", artist: "Gummy" },
      { title: "Breathe", artist: "LEE HI" },
      { title: "HOLO", artist: "LEE HI" },
      { title: "Only", artist: "LEE HI" },
      { title: "그대라는 시", artist: "TAEYEON" },
      { title: "Fine", artist: "TAEYEON" },
      { title: "11:11", artist: "TAEYEON" },
      { title: "Blue", artist: "BIGBANG" },
      { title: "Still Life", artist: "BIGBANG" },
      { title: "You Were Beautiful", artist: "DAY6" },
      { title: "Zombie", artist: "DAY6" },
      { title: "I Need Somebody", artist: "DAY6" },
      { title: "Beautiful", artist: "Crush" },
      { title: "잊어버리지마", artist: "Crush" },
      { title: "Home", artist: "SEVENTEEN" },
      { title: "Hug", artist: "SEVENTEEN" },
      { title: "Magic Shop", artist: "BTS" },
      { title: "Answer: Love Myself", artist: "BTS" },
      { title: "Life Goes On", artist: "BTS" },
      { title: "Spring Day", artist: "BTS" },
      { title: "My Youth", artist: "NCT DREAM" },
      { title: "Rainbow", artist: "NCT DREAM" },
      { title: "That's okay", artist: "D.O." }
    ],

    POP: [
      { title: "Fix You", artist: "Coldplay" },
      { title: "Yellow", artist: "Coldplay" },
      { title: "Paradise", artist: "Coldplay" },
      { title: "Count on Me", artist: "Bruno Mars" },
      { title: "Lean On Me", artist: "Bill Withers" },
      { title: "You Say", artist: "Lauren Daigle" },
      { title: "Rise Up", artist: "Andra Day" },
      { title: "A Million Dreams", artist: "P!nk" },
      { title: "Photograph", artist: "Ed Sheeran" },
      { title: "Perfect", artist: "Ed Sheeran" },
      { title: "Castle on the Hill", artist: "Ed Sheeran" },
      { title: "Vienna", artist: "Billy Joel" },
      { title: "The Climb", artist: "Miley Cyrus" },
      { title: "Fight Song", artist: "Rachel Platten" },
      { title: "Scars To Your Beautiful", artist: "Alessia Cara" },
      { title: "Brave", artist: "Sara Bareilles" },
      { title: "Try", artist: "P!nk" },
      { title: "Keep Holding On", artist: "Avril Lavigne" },
      { title: "A Sky Full of Stars", artist: "Coldplay" },
      { title: "Somewhere Only We Know", artist: "Keane" },
      { title: "Home", artist: "Michael Bublé" },
      { title: "Rainbow", artist: "Kacey Musgraves" },
      { title: "Beautiful", artist: "Christina Aguilera" },
      { title: "You Raise Me Up", artist: "Josh Groban" },
      { title: "Hero", artist: "Mariah Carey" },
      { title: "Stand By Me", artist: "Ben E. King" },
      { title: "What a Wonderful World", artist: "Louis Armstrong" },
      { title: "Here Comes the Sun", artist: "The Beatles" },
      { title: "Let It Be", artist: "The Beatles" },
      { title: "Good Life", artist: "OneRepublic" }
    ]

  },


  "신남": {

    KPOP: [
      { title: "APT.", artist: "ROSÉ & Bruno Mars" },
      { title: "Dynamite", artist: "BTS" },
      { title: "Butter", artist: "BTS" },
      { title: "Fire", artist: "BTS" },
      { title: "MIC Drop", artist: "BTS" },
      { title: "How Sweet", artist: "NewJeans" },
      { title: "Super Shy", artist: "NewJeans" },
      { title: "Hype Boy", artist: "NewJeans" },
      { title: "After LIKE", artist: "IVE" },
      { title: "LOVE DIVE", artist: "IVE" },
      { title: "Baddie", artist: "IVE" },
      { title: "Queencard", artist: "(G)I-DLE" },
      { title: "TOMBOY", artist: "(G)I-DLE" },
      { title: "Super Lady", artist: "(G)I-DLE" },
      { title: "ANTIFRAGILE", artist: "LE SSERAFIM" },
      { title: "UNFORGIVEN", artist: "LE SSERAFIM" },
      { title: "EASY", artist: "LE SSERAFIM" },
      { title: "God's Menu", artist: "Stray Kids" },
      { title: "MANIAC", artist: "Stray Kids" },
      { title: "Thunderous", artist: "Stray Kids" },
      { title: "Wave", artist: "ATEEZ" },
      { title: "Guerrilla", artist: "ATEEZ" },
      { title: "Very Nice", artist: "SEVENTEEN" },
      { title: "Left & Right", artist: "SEVENTEEN" },
      { title: "HOT", artist: "SEVENTEEN" },
      { title: "Red Flavor", artist: "Red Velvet" },
      { title: "Power Up", artist: "Red Velvet" },
      { title: "Dun Dun Dance", artist: "OH MY GIRL" },
      { title: "Energetic", artist: "Wanna One" },
      { title: "I AM", artist: "IVE" }
    ],

    POP: [
      { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars" },
      { title: "Don't Start Now", artist: "Dua Lipa" },
      { title: "Levitating", artist: "Dua Lipa" },
      { title: "Blinding Lights", artist: "The Weeknd" },
      { title: "Cake By The Ocean", artist: "DNCE" },
      { title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
      { title: "24K Magic", artist: "Bruno Mars" },
      { title: "Treasure", artist: "Bruno Mars" },
      { title: "Locked Out of Heaven", artist: "Bruno Mars" },
      { title: "On Top of the World", artist: "Imagine Dragons" },
      { title: "Believer", artist: "Imagine Dragons" },
      { title: "Shut Up and Dance", artist: "WALK THE MOON" },
      { title: "Wake Me Up", artist: "Avicii" },
      { title: "The Nights", artist: "Avicii" },
      { title: "Levels", artist: "Avicii" },
      { title: "Rather Be", artist: "Clean Bandit" },
      { title: "Rather Be", artist: "Clean Bandit ft. Jess Glynne" },
      { title: "Good Time", artist: "Owl City & Carly Rae Jepsen" },
      { title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
      { title: "I Really Like You", artist: "Carly Rae Jepsen" },
      { title: "Dance Monkey", artist: "Tones and I" },
      { title: "Watermelon Sugar", artist: "Harry Styles" },
      { title: "As It Was", artist: "Harry Styles" },
      { title: "Don't Stop Me Now", artist: "Queen" },
      { title: "Dancing Queen", artist: "ABBA" },
      { title: "Mamma Mia", artist: "ABBA" },
      { title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
      { title: "Party Rock Anthem", artist: "LMFAO" },
      { title: "Timber", artist: "Pitbull ft. Kesha" },
      { title: "Firework", artist: "Katy Perry" }
    ]

  },


  "SHARK": {

    KPOP: [
      { title: "Wave", artist: "ATEEZ" },
      { title: "Ocean View", artist: "Rothy" },
      { title: "Island", artist: "WINNER" },
      { title: "Summer Hate", artist: "Zico" },
      { title: "Blue", artist: "BIGBANG" },
      { title: "Summer 127", artist: "NCT 127" },
      { title: "Alcohol-Free", artist: "TWICE" },
      { title: "Dance The Night Away", artist: "TWICE" },
      { title: "Alcohol-Free", artist: "TWICE" },
      { title: "Why So Lonely", artist: "Wonder Girls" },
      { title: "Red Flavor", artist: "Red Velvet" },
      { title: "Power Up", artist: "Red Velvet" },
      { title: "Dolphin", artist: "OH MY GIRL" },
      { title: "Dun Dun Dance", artist: "OH MY GIRL" },
      { title: "Beach Again", artist: "SSAK3" },
      { title: "Travel", artist: "BOL4" },
      { title: "Surf", artist: "ITZY" },
      { title: "ICY", artist: "ITZY" },
      { title: "Island", artist: "WINNER" },
      { title: "View", artist: "SHINee" },
      { title: "Our Summer", artist: "TXT" },
      { title: "Blue Hour", artist: "TXT" },
      { title: "Summer Hate", artist: "Zico" },
      { title: "Pool", artist: "WOODZ" },
      { title: "Wave", artist: "ATEEZ" },
      { title: "Swimming", artist: "Jeon Somi" },
      { title: "Island", artist: "Yerin Baek" },
      { title: "Popo (How deep is our love?)", artist: "Yerin Baek" },
      { title: "Square (2017)", artist: "Yerin Baek" },
      { title: "Every Summertime", artist: "NIKI" }
    ],

    POP: [
      { title: "Ocean Eyes", artist: "Billie Eilish" },
      { title: "Ocean", artist: "Martin Garrix feat. Khalid" },
      { title: "Waves", artist: "Dean Lewis" },
      { title: "Ocean Drive", artist: "Duke Dumont" },
      { title: "A Drop In The Ocean", artist: "Ron Pope" },
      { title: "Watermelon Sugar", artist: "Harry Styles" },
      { title: "Sunroof", artist: "Nicky Youre & dazy" },
      { title: "Island In The Sun", artist: "Weezer" },
      { title: "Walking On A Dream", artist: "Empire of the Sun" },
      { title: "Summer", artist: "Calvin Harris" },
      { title: "Feels", artist: "Calvin Harris ft. Pharrell Williams, Katy Perry & Big Sean" },
      { title: "Cake By The Ocean", artist: "DNCE" },
      { title: "Havana", artist: "Camila Cabello" },
      { title: "Señorita", artist: "Shawn Mendes & Camila Cabello" },
      { title: "Malibu", artist: "Miley Cyrus" },
      { title: "Cruel Summer", artist: "Taylor Swift" },
      { title: "Summertime Sadness", artist: "Lana Del Rey" },
      { title: "California Gurls", artist: "Katy Perry" },
      { title: "Teenage Dream", artist: "Katy Perry" },
      { title: "Riptide", artist: "Vance Joy" },
      { title: "The Ocean", artist: "Mike Perry" },
      { title: "Sunset Lover", artist: "Petit Biscuit" },
      { title: "Firestone", artist: "Kygo ft. Conrad Sewell" },
      { title: "Stole the Show", artist: "Kygo ft. Parson James" },
      { title: "Paradise", artist: "George Ezra" },
      { title: "Island", artist: "The xx" },
      { title: "Feels Like Summer", artist: "Childish Gambino" },
      { title: "Ocean Drive", artist: "Duke Dumont" },
      { title: "A Sky Full of Stars", artist: "Coldplay" },
      { title: "Higher Love", artist: "Kygo & Whitney Houston" }
    ]

  }

};
